# Site settings
title: >
  Classeur â€“ Re-enjoy writing, with Markdown
description: > # this means to ignore newlines until "baseurl:"
  Start writing notes, docs, blogs easily and quickly using Markdown.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://classeur.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
